version: '3.9'
services:
  backend:
    build: ./gymbro-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/gymbro
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
